= nx-rs-docker
:toc: preamble

:icons: font

:ext-rust: https://www.rust-lang.org/
:ext-cargo-nx: https://github.com/aarch64-switch-rs/cargo-nx
:ext-docker-engine: https://docs.docker.com/engine/
:ext-docker-compose: https://docs.docker.com/compose/
:ext-task-go: https://taskfile.dev/

This repository contains necessary files to start development of Nintendo Switch homebrew in Rust using a Docker container.


== Prerequisites
- {ext-rust}[Rust] `^1.75.0` (not used for building)
- {ext-cargo-nx}[`cargo-nx`]
- {ext-docker-engine}[Docker Engine] `^24.0.0`
- {ext-docker-compose}[Docker Compose] `^2.20.2`
- {ext-task-go}[Task] `^3.33.0`


== Files

- `Dockerfile` - Docker image definition based on `ghcr.io/rust-lang/rust:nightly`
- `docker-compose.yaml` - Docker Compose configuration file for volume mounting and easier container control
- `Taskfile` - configuration file for Task runner/build tool (Taskfile for short) to access Rust tooling inside the container


== Installation
:ext-github-cargo-nx-new: https://github.com/aarch64-switch-rs/cargo-nx#new-subcommand

. {ext-github-cargo-nx-new}[Create a new project] using `cargo-nx`.

. Clone this repo as a submodule for you project. I recommend cloning into a `.dev-nx` directory (I shall assume this location further):
+
[source, shell]
----
git submodule add https://github.com/Larento/nx-rs-docker .dev-nx
----

. To use the provided Taskfile in your project, you need to include it inside your own `Taskfile.yaml` file at project root. The simplest one might look like this:
+
[source, yaml]
----
version: '3'
vars:
    INCLUDES_DIR: '.dev-nx' <1>
includes:
    nx:
        taskfile: '{{.INCLUDES_DIR}}/Taskfile.yaml' <2>
        dir: '{{.INCLUDES_DIR}}' <3>
----
<1> `INCLUDES_DIR` - path to submodule directory, from which the Taskfile is included.
<2> The provided Taskfile is included in `nx` namespace (this is just an example, you may choose any name).
<3> It's very important to specify the directory from which the included tasks are executed.
+
To execute tasks from included Taskfile run:
+
[source, shell]
----
task nx:<task-name>
----

. At this point the tree structure of `.dev-nx` directory should look roughly like this:
+
----
. <1>
├── .dev-nx <2>
│   ├── Dockerfile
│   ├── Taskfile.yaml <3>
│   └── docker-compose.yaml
├── Taskfile.yaml <4>
└── ... <5>
----
<1> Project root
<2> Submodule directory
<3> Provided Taskfile
<4> Project Taskfile
<5> The rest of project files


== How it works

. Docker image is built. For reuse purposes, the source code is not copied over at build stage.
. Directories containing the source code `src/` and built binaries `target/` are mounted as bind mounts.
. Project is built using `cargo-nx` inside the container.


== Things to keep in mind
=== Cloning your repository

By default Git won't clone submodules inside a repo. You either need to enable that in global Git settings:

[source, shell]
----
git config --global submodule.recurse true
----

Or clone with `--recurse-submodules` option:

[source, shell]
----
git clone --recurse-submodules <repo>
----


=== Using `rust-analyzer`

To be able to look up function definitions using `rust-analyzer`, you should fetch sources for all crates locally (not in Docker container) with:

[source, shell]
----
cargo fetch
----

In any case, if you are using the provided Taskfile, this is done automatically for you.